### PR TITLE
Use a shim module for strict import

### LINKED ISSUE #1: Feature request: call-site usage of PublicAPI.@strict
Consider the following example:

```julia
import PublicAPI

function foo(x, y, z)
    a = PublicAPI.@strict Upstream.api(x, y, z)
    ...
end
```

If `Upstream.api` has been declared public in the `Upstream.jl` package, then `a = PublicAPI.@strict Upstream.api(x, y, z)` would just turn into `a = Upstream.api(x, y, z)`.

However, if `Upstream.api` has NOT been declared public, then `a = PublicAPI.@strict Upstream.api(x, y, z)` would throw an error.

### PR DESCRIPTION
**Pull request by tkf**
close #1

This implements the strategy I mentioned in https://github.com/JuliaLang/PublicAPI.jl/issues/1#issuecomment-922643365

@DilumAluthge With this PR, all my pending "easy" TODOs are done (others are harder ones like overload API declaration which needs to be designed first). I think it's ready for release for me. But we can also add docs and maybe also should setup other CIs like CompatHelper.jl.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Adding docs before registering the package sounds like a good idea.

I don't think CompatHelper is needed for this repository, given that the package has no dependencies.

**Comment by DilumAluthge** [comment]
A few questions:

1. Am I correct in saying that `PublicAPI.@strict using Module` and `PublicAPI.@strict import Module` do the exact same thing?
2. Would it be possible for us to still support `PublicAPI.@strict using Module: name1, name2, name3`?

**Comment by tkf** [comment]
> I don't think CompatHelper is needed for this repository

Ah, yes! Totally forgot that I cleaned the dependency.

> Am I correct in saying that `PublicAPI.@strict using Module` and `PublicAPI.@strict import Module` do the exact same thing?

Actually, `PublicAPI.@strict using Module` brings the names into the current scope like `using Module` does. It's "strict" in only the sense that `Module.internal_thing` throws. I don't mind removing `PublicAPI.@strict using Module` support, though. This is a good point, given that https://github.com/JuliaLang/julia/pull/42080 started this.

> Would it be possible for us to still support `PublicAPI.@strict using Module: name1, name2, name3`?

Yes, it works as-is after this PR, too.

**Comment by DilumAluthge** [comment]
> > Am I correct in saying that `PublicAPI.@strict using Module` and `PublicAPI.@strict import Module` do the exact same thing?
> 
> Actually, `PublicAPI.@strict using Module` brings the names into the current scope like `using Module` does. It's "strict" in only the sense that `Module.internal_thing` throws. I don't mind removing `PublicAPI.@strict using Module` support, though. This is a good point, given that [JuliaLang/julia#42080](https://github.com/JuliaLang/julia/pull/42080) started this.
> 
> >

Yeah, given https://github.com/JuliaLang/julia/pull/42080, I would prefer that we disallow `PublicAPI.@strict using Module`.

**Comment by DilumAluthge** [comment]
> > Would it be possible for us to still support `PublicAPI.@strict using Module: name1, name2, name3`?
> 
> Yes, it works as-is after this PR, too.

Ok, good! Can we add that back to the docstring?

**Comment by DilumAluthge** [comment]
> > > Would it be possible for us to still support `PublicAPI.@strict using Module: name1, name2, name3`?
> > 
> > 
> > Yes, it works as-is after this PR, too.
> 
> Ok, good! Can we add that back to the docstring?

Never mind, it's still in the docstring. I misread the diff and thought that it had been removed. 😂

**Comment by DilumAluthge** [comment]
Also, since we have the opportunity to be opinionated here, I'd also like it if we can disallow `PublicAPI.@strict import Module: f, g, h`, because this allows people to e.g. extend (add methods to) the `f` function without explicitly qualifying it, which I think can be a source of problems.

**Comment by DilumAluthge** [comment]
Basically, what I would like us to do is this:

Allow the following:
- `PublicAPI.@strict import Module` (which does not bring any names into the current scope)
- `PublicAPI.@strict using Module: name1, name2, name3`

Disallow the following:
- `PublicAPI.@strict using Module`
- `PublicAPI.@strict import Module: name1, name2, name3`

What do you think?

**Comment by tkf** [comment]
Yeah, I agree with the allowed/disallowed examples. I think `PublicAPI.@strict import Module: f, g, h` is disallowed ATM.

In the future, I think it'd be nice to be able to declare "call only API" and "overload only API" and both. It's a TODO

https://github.com/JuliaLang/PublicAPI.jl/blob/28437bf27a56c209fcc09619233e9687b68dcbe2/src/imports.jl#L1-L5

Ideally, it's also possible to denote "ownership" of the argument slot so that we can systematically avoid method ambiguities. But this is a too deep rabbit hole for me to dive into ATM.

Anyway, I think disallowing `PublicAPI.@strict import Module: name1, name2, name3` for now is nice since we can assign a better meaning to it later.

**Comment by DilumAluthge** [comment]
What's left for this PR? I think the only thing left to do is to disallow `PublicAPI.@strict using Module`, and then it's good to merge?

**Comment by tkf** [comment]
Yeah, that was the last item. I just removed it. I'll go ahead and auto-merge.

**Pull request merged**
