### PR TITLE
Also run CI on Julia 1.0

### PR DESCRIPTION
**Pull request by DilumAluthge**
The `Project.toml` file says that the package works on Julia 1.0, so we should run CI on Julia 1.0.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@tkf It doesn't look like the tests are passing on Julia 1.0.

Possible options include:
1. Fix the package so that the tests pass on Julia 1.0.
2. Increase the minimum required Julia version for the package.

**Comment by DilumAluthge** [comment]
On a separate note, it looks like you're running the doctests in all CI jobs, and therefore the doctests are being run on all minor versions of Julia.

If you want, I think it would be reasonable to put the doctests in a separate job, and only run that job with a single minor version of Julia (e.g. `'1'`). It can be hard to keep doctests always passing across multiple minor versions of Julia because of changes to printing and displaying.

**Comment by DilumAluthge** [comment]
Given that `import Foo as Bar` requires Julia 1.6, I think it would be reasonable if you wanted to drop support for Julia < 1.6, especially since 1.6 will be the next LTS.

**Comment by tkf** [comment]
Oops, I fixed things for Julia 1.0 before I saw your comment :)

**Comment by tkf** [comment]
Maybe support 1.0 for now and give people less excuse to not use it?

We can of course drop support once it becomes tedious to fix things for < 1.6.

**Comment by DilumAluthge** [comment]
> Maybe support 1.0 for now and give people less excuse to not use it?
> 
> We can of course drop support once it becomes tedious to fix things for < 1.6.

Sounds good to me!

**Pull request merged**
